const exerciseBank = {
        "עליית תאומים בעמידה כנגד מכונה ייעודית": "https://youtube.com/shorts/uY38-st6rj8",
        "עליית תאומים בעמידה על מדרגה כנגד משקולת יד": "https://www.youtube.com/shorts/n-5T_oYc1oU",
        "עליית תאומים בישיבה כנגד מכשיר לחיצת רגליים": "https://youtu.be/dhRz1Ns60Zg",
        "עליית תאומים בעמידה על מדרגה כנגד כבל פולי תחתון עם ידית": "https://youtu.be/epF7bNRSa-U",
        "כפיפת ברך בישיבה כנגד מכונה ייעודית": "https://youtube.com/shorts/_lgE0gPvbik",
        "כפיפת ברך בשכיבה על הבטן כנגד מכונה ייעודית": "https://youtube.com/shorts/lGNeJsdqJwg",
        "כפיפת ברך נורדית": "https://youtube.com/shorts/7o_-YMUdLdM",
        "כפיפת ברך בעמידה כנגד מכונה ייעודית": "https://youtube.com/shorts/IwcLkHuH7iw",
        "פשיטת ברך בישיבה כנגד מכונה ייעודית": "https://youtube.com/shorts/w72YiHz15CA",
        "פשיטת ירך בעמידה עם הטיית גו כנגד כבל פולי תחתון עם רצועת קרסול": "https://youtube.com/shorts/A9aN_L4vexk",
        "הרחקת ירך בישיבה כנגד מכונה ייעודית": "https://youtube.com/shorts/WOv7Aca6r-0?si=gCbV-jIhzbcSUjIl",
        "קירוב ירך בישיבה כנגד מכונה ייעודית": "https://youtube.com/shorts/BmMmt-c9aNM",
        "כפיפת בטן בישיבה כנגד מכונה ייעודית": "https://youtube.com/shorts/mnRhbUB3Fjs",
        "כפיפת בטן בכריעה על הברכיים כנגד כבל פולי עליון עם ידיות": "https://youtube.com/shorts/dkGwcfo9zto",
        "כפיפת בטן בשכיבה על מזרון": "https://youtu.be/eeJ_CYqSoT4",
        "כפיפת עמוד שדרה צידית בשכיבה על מזרון": "https://youtu.be/q0QyCrpiNgI",
        "כפיפת עמוד שדרה צידית בפלאנק צידי על מזרון": "https://youtube.com/shorts/F63KKkm18xw",
        "הרמת שכמות בעמידה כנגד משקולות יד": "https://youtube.com/shorts/rFsSeClGnNA",
        "הרמת שכמות בעמידה כנגד מוט חופשי": "https://youtube.com/shorts/MlqHEfydPpE",
        "הרמת שכמות בעמידה כנגד כבל פולי תחתון": "https://youtube.com/shorts/JxaV9n9l2Y8",
        "כפיפת שורש כף היד בכריעה על ספסל כנגד משקולות יד": "https://youtu.be/3VLTzIrnb5g",
        "כפיפה גבית בשורש כף היד בהישענות על ספסל כנגד משקולת יד": "https://youtube.com/shorts/xENVg7RX_O8",
        "כפיפת שורש כף היד בעמידה כנגד מוט חופשי מאחורי הגב": "https://youtube.com/shorts/jPsOEeTt_Js",
        "כפיפה גבית בשורש כף היד בישיבה עם האמות על הברכיים כנגד מוט חופשי": "https://youtube.com/shorts/lCDJzXn2UFU",
        "כפיפת מרפק בעמידה כנגד משקולות יד": "https://youtube.com/shorts/2jpteC44QKg",
        "כפיפת מרפק בישיבה על ספסל בשיפוע חיובי כנגד משקולות יד": "https://youtu.be/HhHHBj3qTJ4",
        "כפיפת מרפק עם יד אחת בכיסא כומר כנגד משקולת יד": "https://youtube.com/shorts/Mv-KfOHYnGg?si=LxjIlk4qwSkr5PBp",
        "כפיפת מרפק בעמידה כנגד משקולות יד באחיזת פטיש": "https://youtu.be/RIEMoYL_h1Y",
        "כפיפת מרפק בעמידה כנגד כבל פולי תחתון עם חבל באחיזת פטיש": "https://youtube.com/shorts/YC9QZiti-40",
        "כפיפת מרפק בשכיבה על החזה על ספסל בשיפוע חיובי כנגד משקולות יד": "https://youtube.com/shorts/ivS3G35bapw",
        "פשיטת מרפק מעל הראש בעמידה כנגד שני כבלי פולי אמצעי בהצלבה": "https://youtube.com/shorts/3UbUoDcmSsU",
        "פשיטת מרפק בעמידה כנגד כבל פולי עליון עם מוט": "https://youtu.be/-zLyUAo1gMw",
        "פשיטת מרפק בעמידה כנגד כבל פולי עליון עם חבל": "https://youtube.com/shorts/4NWWB0f0vzQ",
        "פשיטת מרפק מעל הראש בעמידה כנגד כבל פולי תחתון עם חבל": "https://youtube.com/shorts/9Ark9S11uXw",
        "פשיטת מרפק בעמידה עם יד אחת כנגד כבל פולי עליון עם ידית": "https://youtube.com/shorts/LsFfSa7TsAg",
        "הרחקת כתף אופקית בישיבה כנגד מכונה ייעודית": "https://youtube.com/shorts/7tgx6QHB0-A",
        "הרחקת כתף אופקית בעמידה כנגד כבל פולי עליון": "https://youtube.com/shorts/bkejPHrPkmA",
        "הרחקת כתף צידית בעמידה כנגד משקולות יד": "https://youtu.be/PzsMitRdI_8",
        "הרחקת כתף צידית בעמידה כנגד כבל פולי תחתון": "https://youtube.com/shorts/lMJUXEvcMkQ",
        "פרפר בישיבה כנגד מכונה ייעודית": "https://youtu.be/3jYo5cMU3d4",
        "פרפר בישיבה כנגד כבל פולי אמצעי": "https://youtu.be/2sO5ZlpqUh0",
        "סקוואט בולגרי בעמידה כנגד משקולות יד": "https://youtu.be/SkNsa3eBwLA",
        "סקוואט בעמידה כנגד מוט חופשי": "https://youtu.be/aOzrA4FgnM0",
        "דדליפט רומני כנגד מוט חופשי": "https://youtu.be/3VXmecChYYM",
        "דדליפט רומני כנגד משקולות יד": "https://youtube.com/shorts/OBNPP1Wl8KA",
        "היפ טראסט כנגד מוט חופשי": "https://youtube.com/shorts/42lU8xsumBo?si=WXUfZ2n5mRhRWwrc",
        "היפ טראסט כנגד מכונת סמיט": "https://youtube.com/shorts/g_LQtNepgo0",
        "מכרעים בהליכה כנגד משקולות יד": "https://youtu.be/Pbmj6xPo-Hw",
        "לחיצת רגליים כנגד מכונה ייעודית": "https://youtube.com/shorts/nDh_BlnLCGc",
        "סקוואט בעמידה כנגד מכונת פנדולום": "https://youtube.com/shorts/RE9k04SVWOo",
        "סקוואט בהישענות כנגד מכונת האק": "https://youtube.com/shorts/fl4PtdimZSk",
        "דדליפט כנגד מוט חופשי": "https://youtube.com/shorts/ZaTM37cfiDs",
        "לחיצת כתפיים בישיבה כנגד משקולות יד": "https://youtu.be/rO_iEImwHyo",
        "לחיצת כתפיים בישיבה כנגד מוט במכונת סמיט": "https://youtube.com/shorts/E7ngsffMPR0",
        "לחיצת חזה בשכיבה בשיפוע חיובי כנגד משקולות יד": "https://youtu.be/IP4oeKh1Sd4",
        "שכיבות סמיכה": "https://youtu.be/F0mFvxZelaE",
        "מקבילים": "https://youtu.be/TrJVszDm7ik",
        "לחיצת חזה בשכיבה כנגד מוט חופשי": "https://youtu.be/lWFknlOTbyM",
        "לחיצת חזה בשכיבה בשיפוע חיובי כנגד מוט חופשי": "https://youtube.com/shorts/98HWfiRonkE",
        "לחיצת חזה בשכיבה כנגד משקולות יד": "https://youtube.com/shorts/mTaiQemkEpU",
        "לחיצת חזה בישיבה כנגד כבל פולי תחתון": "https://youtube.com/shorts/NcF_JFHEry0",
        "לחיצת חזה בישיבה כנגד כבל פולי אמצעי": "https://youtube.com/shorts/-wubBe3IYnQ",
        "לחיצת חזה בישיבה כנגד מכונה ייעודית": "https://youtube.com/shorts/E8iUR2lhgR8",
        "לחיצת חזה בישיבה בשיפוע חיובי כנגד מכונה ייעודית": "https://youtu.be/VesHgJR14E8",
        "מקבילים בישיבה כנגד מכונה ייעודית": "https://youtube.com/shorts/dnS3_CqhT2o",
        "חתירה בישיבה כנגד כבל פולי תחתון": "https://youtu.be/vwHG9Jfu4sw",
        "חתירה בכריעת ברך עם יד אחת כנגד כבל פולי אמצעי": "https://youtube.com/shorts/9TWiV80cUYs",
        "משיכת פולי עליון בישיבה עם אחיזת וי": "https://youtube.com/shorts/jXRxMJhOCc0",
        "משיכת פולי עליון בישיבה על ספסל עם יד אחת": "https://youtube.com/shorts/0VDkEX5RBC8",
        "משיכת פולי עליון בישיבה באחיזה רחבה": "https://youtube.com/shorts/bNmvKpJSWKM?si=sOQuy7T0_gDesNYf",
        "חתירה בכריעת ברך על ספסל כנגד משקולת יד": "https://youtu.be/dFzUjzfih7k",
        "חתירה בהטיית גו כנגד מוט חופשי": "https://youtu.be/FWJR5Ve8bnQ",
        "חתירה בישיבה עם יד אחת כנגד מכונה ייעודית": "https://youtu.be/XKctRJRN5LQ",
        "פייס פולס בעמידה כנגד כבל פולי עליון עם חבל": "https://youtube.com/shorts/IeOqdw9WI90",
        "עליות מתח": "https://youtube.com/shorts/eDP_OOhMTZ4"
    };

    // מיפוי כל תרגיל ב-exerciseBank לקטגוריית שריר, לשימוש בבניית תוכנית custom
    const exerciseCategories = {
        "עליית תאומים בעמידה כנגד מכונה ייעודית": "רגליים",
        "עליית תאומים בעמידה על מדרגה כנגד משקולת יד": "רגליים",
        "עליית תאומים בישיבה כנגד מכשיר לחיצת רגליים": "רגליים",
        "עליית תאומים בעמידה על מדרגה כנגד כבל פולי תחתון עם ידית": "רגליים",
        "כפיפת ברך בישיבה כנגד מכונה ייעודית": "רגליים",
        "כפיפת ברך בשכיבה על הבטן כנגד מכונה ייעודית": "רגליים",
        "כפיפת ברך נורדית": "רגליים",
        "כפיפת ברך בעמידה כנגד מכונה ייעודית": "רגליים",
        "פשיטת ברך בישיבה כנגד מכונה ייעודית": "רגליים",
        "פשיטת ירך בעמידה עם הטיית גו כנגד כבל פולי תחתון עם רצועת קרסול": "ישבן",
        "הרחקת ירך בישיבה כנגד מכונה ייעודית": "ישבן",
        "קירוב ירך בישיבה כנגד מכונה ייעודית": "רגליים",
        "כפיפת בטן בישיבה כנגד מכונה ייעודית": "בטן",
        "כפיפת בטן בכריעה על הברכיים כנגד כבל פולי עליון עם ידיות": "בטן",
        "כפיפת בטן בשכיבה על מזרון": "בטן",
        "כפיפת עמוד שדרה צידית בשכיבה על מזרון": "בטן",
        "כפיפת עמוד שדרה צידית בפלאנק צידי על מזרון": "בטן",
        "הרמת שכמות בעמידה כנגד משקולות יד": "גב",
        "הרמת שכמות בעמידה כנגד מוט חופשי": "גב",
        "הרמת שכמות בעמידה כנגד כבל פולי תחתון": "גב",
        "כפיפת שורש כף היד בכריעה על ספסל כנגד משקולות יד": "יד קדמית",
        "כפיפה גבית בשורש כף היד בהישענות על ספסל כנגד משקולת יד": "יד אחורית",
        "כפיפת שורש כף היד בעמידה כנגד מוט חופשי מאחורי הגב": "יד קדמית",
        "כפיפה גבית בשורש כף היד בישיבה עם האמות על הברכיים כנגד מוט חופשי": "יד אחורית",
        "כפיפת מרפק בעמידה כנגד משקולות יד": "יד קדמית",
        "כפיפת מרפק בישיבה על ספסל בשיפוע חיובי כנגד משקולות יד": "יד קדמית",
        "כפיפת מרפק עם יד אחת בכיסא כומר כנגד משקולת יד": "יד קדמית",
        "כפיפת מרפק בעמידה כנגד משקולות יד באחיזת פטיש": "יד קדמית",
        "כפיפת מרפק בעמידה כנגד כבל פולי תחתון עם חבל באחיזת פטיש": "יד קדמית",
        "כפיפת מרפק בשכיבה על החזה על ספסל בשיפוע חיובי כנגד משקולות יד": "יד קדמית",
        "פשיטת מרפק מעל הראש בעמידה כנגד שני כבלי פולי אמצעי בהצלבה": "יד אחורית",
        "פשיטת מרפק בעמידה כנגד כבל פולי עליון עם מוט": "יד אחורית",
        "פשיטת מרפק בעמידה כנגד כבל פולי עליון עם חבל": "יד אחורית",
        "פשיטת מרפק מעל הראש בעמידה כנגד כבל פולי תחתון עם חבל": "יד אחורית",
        "פשיטת מרפק בעמידה עם יד אחת כנגד כבל פולי עליון עם ידית": "יד אחורית",
        "הרחקת כתף אופקית בישיבה כנגד מכונה ייעודית": "כתפיים",
        "הרחקת כתף אופקית בעמידה כנגד כבל פולי עליון": "כתפיים",
        "הרחקת כתף צידית בעמידה כנגד משקולות יד": "כתפיים",
        "הרחקת כתף צידית בעמידה כנגד כבל פולי תחתון": "כתפיים",
        "פרפר בישיבה כנגד מכונה ייעודית": "חזה",
        "פרפר בישיבה כנגד כבל פולי אמצעי": "חזה",
        "סקוואט בולגרי בעמידה כנגד משקולות יד": "רגליים",
        "סקוואט בעמידה כנגד מוט חופשי": "רגליים",
        "דדליפט רומני כנגד מוט חופשי": "ישבן",
        "דדליפט רומני כנגד משקולות יד": "ישבן",
        "היפ טראסט כנגד מוט חופשי": "ישבן",
        "היפ טראסט כנגד מכונת סמיט": "ישבן",
        "מכרעים בהליכה כנגד משקולות יד": "רגליים",
        "לחיצת רגליים כנגד מכונה ייעודית": "רגליים",
        "סקוואט בעמידה כנגד מכונת פנדולום": "רגליים",
        "סקוואט בהישענות כנגד מכונת האק": "רגליים",
        "דדליפט כנגד מוט חופשי": "גב",
        "לחיצת כתפיים בישיבה כנגד משקולות יד": "כתפיים",
        "לחיצת כתפיים בישיבה כנגד מוט במכונת סמיט": "כתפיים",
        "לחיצת חזה בשכיבה בשיפוע חיובי כנגד משקולות יד": "חזה",
        "שכיבות סמיכה": "חזה",
        "מקבילים": "חזה",
        "לחיצת חזה בשכיבה כנגד מוט חופשי": "חזה",
        "לחיצת חזה בשכיבה בשיפוע חיובי כנגד מוט חופשי": "חזה",
        "לחיצת חזה בשכיבה כנגד משקולות יד": "חזה",
        "לחיצת חזה בישיבה כנגד כבל פולי תחתון": "חזה",
        "לחיצת חזה בישיבה כנגד כבל פולי אמצעי": "חזה",
        "לחיצת חזה בישיבה כנגד מכונה ייעודית": "חזה",
        "לחיצת חזה בישיבה בשיפוע חיובי כנגד מכונה ייעודית": "חזה",
        "מקבילים בישיבה כנגד מכונה ייעודית": "חזה",
        "חתירה בישיבה כנגד כבל פולי תחתון": "גב",
        "חתירה בכריעת ברך עם יד אחת כנגד כבל פולי אמצעי": "גב",
        "משיכת פולי עליון בישיבה עם אחיזת וי": "גב",
        "משיכת פולי עליון בישיבה על ספסל עם יד אחת": "גב",
        "משיכת פולי עליון בישיבה באחיזה רחבה": "גב",
        "חתירה בכריעת ברך על ספסל כנגד משקולת יד": "גב",
        "חתירה בהטיית גו כנגד מוט חופשי": "גב",
        "חתירה בישיבה עם יד אחת כנגד מכונה ייעודית": "גב",
        "פייס פולס בעמידה כנגד כבל פולי עליון עם חבל": "כתפיים",
        "עליות מתח": "גב"
    };

    // סוגי אירובי (self-serve, ר' cardioSchedule ב-app-workouts.js) — רשימה סגורה, אושרה עם המשתמש
    const CARDIO_TYPES = {
        treadmill: { label: "הליכון",    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="15" width="18" height="4" rx="1.5"/><path d="M6 15v-2.5A2.5 2.5 0 0 1 8.5 10H16a3 3 0 0 1 3 3v2"/><circle cx="9" cy="8" r="1.5"/></svg>' },
        bike:      { label: "אופניים",   icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="17" r="3.3"/><circle cx="18" cy="17" r="3.3"/><path d="M6 17l3-8h4l4 8"/><path d="M10 9V6"/><path d="M9 6h2.5"/></svg>' },
        jumprope:  { label: "חבל קפיצה", icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M4 6c3 0 3 12 8 12s5-12 8-12"/><circle cx="4" cy="6" r="1.4"/><circle cx="20" cy="6" r="1.4"/></svg>' },
        run:       { label: "ריצה",      icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><circle cx="16" cy="5" r="1.6"/><path d="M9 20l2.5-5 2-2-1.5-5-4 1.5"/><path d="M11.5 15l3.5 1 3-4.5"/><path d="M8 11l-3 2"/></svg>' },
        row:       { label: "חתירה",     icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M3 17h18"/><rect x="5" y="15" width="4" height="2" rx="0.5"/><path d="M9 16l6-4"/><circle cx="16" cy="11" r="1.6"/></svg>' },
        walk:      { label: "הליכה",     icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="4.5" r="1.6"/><path d="M12 6.5v5"/><path d="M12 11.5l-3 5.5"/><path d="M12 11.5l3.5 4"/><path d="M12 8l-3 2"/><path d="M12 8l3 1.5"/></svg>' },
        elliptical:{ label: "מכשיר אליפטי", icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="10" cy="16" rx="7" ry="2.3"/><path d="M6 15L11 6"/><path d="M14 15L11 6"/><circle cx="11" cy="6" r="1.3"/></svg>' },
        swim:      { label: "שחייה",     icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><circle cx="5" cy="9" r="1.5"/><path d="M5 10.5c1.5 0 2 2 4.5 2s3.5-3 6-2"/><path d="M2 17c2-1.5 4-1.5 6 0s4 1.5 6 0 4-1.5 6 0" stroke-width="1.4"/></svg>' },
        stairs:    { label: "מדרגות",    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19h3v-3h3v-3h3v-3h3v-3h3"/></svg>' },
        other:     { label: "אחר",       icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="12" r="1.4"/><circle cx="12" cy="12" r="1.4"/><circle cx="18" cy="12" r="1.4"/></svg>' },
    };

    // תבניות אימון מוכנות מראש (9 תבניות + custom נספר בנפרד ב-UI).
    // כל תבנית: { id, name, workoutsPerWeek, workoutA/B/C/..., workoutDays: {A:[0-6],...}, cardioPlan: {A:{description,duration},...} }
    const workoutTemplates = [
        {
            id: 1,
            name: "מתחילים · 3 ימים",
            split: "כל הגוף",
            workoutsPerWeek: 3,
            workoutA: [
                { name: "לחיצת חזה בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בישיבה עם יד אחת כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת כתפיים בישיבה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "לחיצת רגליים כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת בטן בשכיבה על מזרון", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "עליית תאומים בעמידה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutB: [
                { name: "לחיצת חזה בשכיבה בשיפוע חיובי כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "משיכת פולי עליון בישיבה עם אחיזת וי", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרחקת כתף צידית בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "היפ טראסט כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "כפיפת עמוד שדרה צידית בשכיבה על מזרון", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "עליית תאומים בעמידה על מדרגה כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutC: [
                { name: "מקבילים בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בהטיית גו כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "לחיצת כתפיים בישיבה כנגד מוט במכונת סמיט", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "דדליפט רומני כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "כפיפת שורש כף היד בכריעה על ספסל כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרמת שכמות בעמידה כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutDays: { A: [0], B: [2], C: [4] },
            cardioPlan: {},
        },
        {
            id: 2,
            name: "מתחילים · 4 ימים",
            split: "עליון ותחתון",
            workoutsPerWeek: 4,
            workoutA: [
                { name: "לחיצת חזה בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בהטיית גו כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת כתפיים בישיבה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת שורש כף היד בעמידה כנגד מוט חופשי מאחורי הגב", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פשיטת מרפק בעמידה כנגד כבל פולי עליון עם חבל", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרמת שכמות בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutB: [
                { name: "סקוואט בעמידה כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "כפיפת ברך בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "היפ טראסט כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "עליית תאומים בעמידה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "כפיפת בטן בשכיבה על מזרון", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutC: [
                { name: "לחיצת חזה בשכיבה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "משיכת פולי עליון בישיבה באחיזה רחבה", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "הרחקת כתף צידית בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת מרפק בעמידה כנגד משקולות יד באחיזת פטיש", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפה גבית בשורש כף היד בהישענות על ספסל כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutD: [
                { name: "לחיצת רגליים כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "דדליפט רומני כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "פשיטת ירך בעמידה עם הטיית גו כנגד כבל פולי תחתון עם רצועת קרסול", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "עליית תאומים בעמידה על מדרגה כנגד כבל פולי תחתון עם ידית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "כפיפת עמוד שדרה צידית בשכיבה על מזרון", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutDays: { A: [0], B: [1], C: [3], D: [4] },
            cardioPlan: {},
        },
        {
            id: 3,
            name: "מתחילים · 5 ימים",
            split: "עליון, תחתון וגוף מלא",
            workoutsPerWeek: 5,
            workoutA: [
                { name: "לחיצת חזה בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בהטיית גו כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת כתפיים בישיבה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת שורש כף היד בכריעה על ספסל כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פשיטת מרפק בעמידה כנגד כבל פולי עליון עם מוט", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרמת שכמות בעמידה כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutB: [
                { name: "סקוואט בעמידה כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "כפיפת ברך בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "היפ טראסט כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "עליית תאומים בעמידה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
            ],
            workoutC: [
                { name: "מקבילים בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "משיכת פולי עליון בישיבה עם אחיזת וי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "הרחקת כתף צידית בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "לחיצת רגליים כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "כפיפת בטן בשכיבה על מזרון", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutD: [
                { name: "לחיצת חזה בישיבה כנגד כבל פולי אמצעי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בישיבה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת כתפיים בישיבה כנגד מוט במכונת סמיט", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת מרפק עם יד אחת בכיסא כומר כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפה גבית בשורש כף היד בישיבה עם האמות על הברכיים כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutE: [
                { name: "מכרעים בהליכה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "דדליפט רומני כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "עליית תאומים בעמידה על מדרגה כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "כפיפת עמוד שדרה צידית בשכיבה על מזרון", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "קירוב ירך בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutDays: { A: [0], B: [1], C: [2], D: [4], E: [5] },
            cardioPlan: {},
        },
        {
            id: 4,
            name: "מתקדם · 3 ימים",
            split: "כל הגוף",
            workoutsPerWeek: 3,
            workoutA: [
                { name: "לחיצת חזה בשכיבה בשיפוע חיובי כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "עליות מתח", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרחקת כתף צידית בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "סקוואט בולגרי בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "כפיפת עמוד שדרה צידית בפלאנק צידי על מזרון", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "עליית תאומים בעמידה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutB: [
                { name: "לחיצת חזה בישיבה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "חתירה בכריעת ברך על ספסל כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "לחיצת כתפיים בישיבה כנגד מוט במכונת סמיט", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "דדליפט רומני כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת ברך בשכיבה על הבטן כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת מרפק בשכיבה על החזה על ספסל בשיפוע חיובי כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרמת שכמות בעמידה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutC: [
                { name: "מקבילים", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "דדליפט כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "הרחקת כתף אופקית בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "סקוואט בהישענות כנגד מכונת האק", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פשיטת מרפק בעמידה עם יד אחת כנגד כבל פולי עליון עם ידית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "עליית תאומים בעמידה על מדרגה כנגד כבל פולי תחתון עם ידית", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutDays: { A: [0], B: [2], C: [4] },
            cardioPlan: {},
        },
        {
            id: 5,
            name: "מתקדם · 4 ימים",
            split: "עליון ותחתון",
            workoutsPerWeek: 4,
            workoutA: [
                { name: "לחיצת חזה בשכיבה בשיפוע חיובי כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "פרפר בישיבה כנגד כבל פולי אמצעי", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "חתירה בהטיית גו כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "משיכת פולי עליון בישיבה באחיזה רחבה", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "לחיצת כתפיים בישיבה כנגד מוט במכונת סמיט", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרמת שכמות בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutB: [
                { name: "סקוואט בעמידה כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "מכרעים בהליכה כנגד משקולות יד", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "כפיפת ברך בשכיבה על הבטן כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "עליית תאומים בישיבה כנגד מכשיר לחיצת רגליים", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "כפיפת בטן בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutC: [
                { name: "לחיצת חזה בישיבה בשיפוע חיובי כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בכריעת ברך עם יד אחת כנגד כבל פולי אמצעי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "פייס פולס בעמידה כנגד כבל פולי עליון עם חבל", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת שורש כף היד בעמידה כנגד מוט חופשי מאחורי הגב", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפה גבית בשורש כף היד בהישענות על ספסל כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutD: [
                { name: "לחיצת רגליים כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "היפ טראסט כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "דדליפט רומני כנגד משקולות יד", reps: "10-15", warmupSets: 0, workSets: 3 },
                { name: "קירוב ירך בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "עליית תאומים בעמידה על מדרגה כנגד כבל פולי תחתון עם ידית", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutDays: { A: [0], B: [1], C: [3], D: [4] },
            cardioPlan: {},
        },
        {
            id: 6,
            name: "מתקדם · 5 ימים",
            split: "דחיפה, משיכה, רגליים, עליון ותחתון",
            workoutsPerWeek: 5,
            workoutA: [
                { name: "לחיצת חזה בשכיבה בשיפוע חיובי כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת חזה בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "פרפר בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "לחיצת כתפיים בישיבה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרחקת כתף צידית בעמידה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פשיטת מרפק בעמידה כנגד כבל פולי עליון עם חבל", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutB: [
                { name: "דדליפט כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בהטיית גו כנגד מוט חופשי", reps: "10-15", warmupSets: 0, workSets: 3 },
                { name: "משיכת פולי עליון בישיבה עם אחיזת וי", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "כפיפת שורש כף היד בכריעה על ספסל כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת מרפק בעמידה כנגד כבל פולי תחתון עם חבל באחיזת פטיש", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "הרמת שכמות בעמידה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutC: [
                { name: "סקוואט בעמידה כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "סקוואט בהישענות כנגד מכונת האק", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "כפיפת ברך בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "היפ טראסט כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "עליית תאומים בעמידה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
            ],
            workoutD: [
                { name: "לחיצת חזה בישיבה כנגד כבל פולי אמצעי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בישיבה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת כתפיים בישיבה כנגד מוט במכונת סמיט", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת מרפק עם יד אחת בכיסא כומר כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפה גבית בשורש כף היד בישיבה עם האמות על הברכיים כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutE: [
                { name: "לחיצת רגליים כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "מכרעים בהליכה כנגד משקולות יד", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "דדליפט רומני כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "עליית תאומים בעמידה על מדרגה כנגד כבל פולי תחתון עם ידית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת בטן בשכיבה על מזרון", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutDays: { A: [0], B: [1], C: [2], D: [4], E: [5] },
            cardioPlan: {},
        },
        {
            id: 7,
            name: "מתקדם · 5 ימים",
            split: "חזה וגב, כתפיים וידיים, רגליים",
            workoutsPerWeek: 5,
            workoutA: [
                { name: "לחיצת חזה בשכיבה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בכריעת ברך על ספסל כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת חזה בישיבה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "משיכת פולי עליון בישיבה על ספסל עם יד אחת", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "הרמת שכמות בעמידה כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutB: [
                { name: "סקוואט בולגרי בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "סקוואט בעמידה כנגד מכונת פנדולום", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "כפיפת ברך נורדית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פשיטת ירך בעמידה עם הטיית גו כנגד כבל פולי תחתון עם רצועת קרסול", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "עליית תאומים בעמידה על מדרגה כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 3 },
            ],
            workoutC: [
                { name: "לחיצת כתפיים בישיבה כנגד מוט במכונת סמיט", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "הרחקת כתף צידית בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרחקת כתף אופקית בעמידה כנגד כבל פולי עליון", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת מרפק בישיבה על ספסל בשיפוע חיובי כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פשיטת מרפק בעמידה עם יד אחת כנגד כבל פולי עליון עם ידית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פייס פולס בעמידה כנגד כבל פולי עליון עם חבל", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutD: [
                { name: "שכיבות סמיכה", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "עליות מתח", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת חזה בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "חתירה בכריעת ברך עם יד אחת כנגד כבל פולי אמצעי", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "הרמת שכמות בעמידה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutE: [
                { name: "סקוואט בעמידה כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת רגליים כנגד מכונה ייעודית", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "דדליפט רומני כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "קירוב ירך בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "עליית תאומים בעמידה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת בטן בשכיבה על מזרון", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutDays: { A: [0], B: [1], C: [2], D: [4], E: [5] },
            cardioPlan: {},
        },
        {
            id: 8,
            name: "מתקדם · 6 ימים",
            split: "דחיפה, משיכה ורגליים",
            workoutsPerWeek: 6,
            workoutA: [
                { name: "לחיצת חזה בשכיבה בשיפוע חיובי כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת חזה בישיבה בשיפוע חיובי כנגד מכונה ייעודית", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "לחיצת כתפיים בישיבה כנגד מוט במכונת סמיט", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרחקת כתף צידית בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פשיטת מרפק מעל הראש בעמידה כנגד כבל פולי תחתון עם חבל", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פרפר בישיבה כנגד כבל פולי אמצעי", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutB: [
                { name: "דדליפט כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בהטיית גו כנגד מוט חופשי", reps: "10-15", warmupSets: 0, workSets: 3 },
                { name: "משיכת פולי עליון בישיבה באחיזה רחבה", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "כפיפת שורש כף היד בעמידה כנגד מוט חופשי מאחורי הגב", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת מרפק בעמידה כנגד כבל פולי תחתון עם חבל באחיזת פטיש", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutC: [
                { name: "סקוואט בעמידה כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "מכרעים בהליכה כנגד משקולות יד", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "כפיפת ברך בשכיבה על הבטן כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "עליית תאומים בעמידה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת בטן בשכיבה על מזרון", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutD: [
                { name: "לחיצת חזה בישיבה כנגד כבל פולי אמצעי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "מקבילים בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "הרחקת כתף צידית בעמידה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פייס פולס בעמידה כנגד כבל פולי עליון עם חבל", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפה גבית בשורש כף היד בישיבה עם האמות על הברכיים כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פשיטת מרפק בעמידה כנגד כבל פולי עליון עם מוט", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutE: [
                { name: "חתירה בישיבה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "משיכת פולי עליון בישיבה עם אחיזת וי", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "חתירה בכריעת ברך עם יד אחת כנגד כבל פולי אמצעי", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "הרמת שכמות בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת מרפק בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת מרפק בשכיבה על החזה על ספסל בשיפוע חיובי כנגד משקולות יד", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutF: [
                { name: "לחיצת רגליים כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "סקוואט בעמידה כנגד מכונת פנדולום", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "דדליפט רומני כנגד מוט חופשי", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "היפ טראסט כנגד מכונת סמיט", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "עליית תאומים בעמידה על מדרגה כנגד כבל פולי תחתון עם ידית", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutDays: { A: [0], B: [1], C: [2], D: [3], E: [4], F: [5] },
            cardioPlan: {},
        },
        {
            id: 9,
            name: "מתקדם · 6 ימים",
            split: "דחיפה, משיכה, רגליים, עליון, תחתון וגוף מלא",
            workoutsPerWeek: 6,
            workoutA: [
                { name: "שכיבות סמיכה", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת חזה בישיבה בשיפוע חיובי כנגד מכונה ייעודית", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "לחיצת כתפיים בישיבה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרחקת כתף אופקית בעמידה כנגד כבל פולי עליון", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פשיטת מרפק בעמידה עם יד אחת כנגד כבל פולי עליון עם ידית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "פשיטת מרפק מעל הראש בעמידה כנגד שני כבלי פולי אמצעי בהצלבה", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutB: [
                { name: "עליות מתח", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בכריעת ברך על ספסל כנגד משקולת יד", reps: "10-15", warmupSets: 0, workSets: 3 },
                { name: "הרמת שכמות בעמידה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת מרפק עם יד אחת בכיסא כומר כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת מרפק בעמידה כנגד משקולות יד באחיזת פטיש", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutC: [
                { name: "סקוואט בהישענות כנגד מכונת האק", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "סקוואט בולגרי בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 0, workSets: 2 },
                { name: "כפיפת ברך נורדית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "קירוב ירך בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "עליית תאומים בישיבה כנגד מכשיר לחיצת רגליים", reps: "10-15", warmupSets: 1, workSets: 3 },
            ],
            workoutD: [
                { name: "לחיצת חזה בשכיבה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "חתירה בישיבה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "לחיצת כתפיים בישיבה כנגד מוט במכונת סמיט", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת שורש כף היד בכריעה על ספסל כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפה גבית בשורש כף היד בהישענות על ספסל כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 2 },
            ],
            workoutE: [
                { name: "לחיצת רגליים כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "כפיפת ברך בישיבה כנגד מכונה ייעודית", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "פשיטת ירך בעמידה עם הטיית גו כנגד כבל פולי תחתון עם רצועת קרסול", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "עליית תאומים בעמידה על מדרגה כנגד משקולת יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת עמוד שדרה צידית בפלאנק צידי על מזרון", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutF: [
                { name: "לחיצת חזה בישיבה כנגד כבל פולי תחתון", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "משיכת פולי עליון בישיבה על ספסל עם יד אחת", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "הרחקת כתף צידית בעמידה כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "סקוואט בעמידה כנגד מכונת פנדולום", reps: "10-15", warmupSets: 1, workSets: 3 },
                { name: "דדליפט רומני כנגד משקולות יד", reps: "10-15", warmupSets: 1, workSets: 2 },
                { name: "כפיפת בטן בכריעה על הברכיים כנגד כבל פולי עליון עם ידיות", reps: "10-15", warmupSets: 0, workSets: 2 },
            ],
            workoutDays: { A: [0], B: [1], C: [2], D: [3], E: [4], F: [5] },
            cardioPlan: {},
        },
    ];

const faqData = [
    {
        category: "תזונה, אסטרטגיה ואורח חיים",
        questions: [
            { q: "איך להתנהל כשיוצאים למסעדה או לאירוע?", a: "אל תבטלו תוכניות חברתיות, התהליך אמור להשתלב בחיים שלכם ולא להפך. ביום של אירוע, מומלץ לאכול ארוחות מבוססות חלבון וירקות במהלך היום כדי 'לשמור' קלוריות וערכים לערב. במסעדה, העדיפו מנות שקל להבין מה הן מכילות (כמו נתח בשרי/דג עם תוספת פחמימה בצד) ונסו לבקש את הרטבים בכלי נפרד כדי לשלוט בכמות. הכי חשוב, אל תגיעו לאירוע מורעבים, זה הדבר שהכי מוביל לבחירות פחות טובות." },
            { q: "מה עושים אם יוצאים לחופשה של כמה ימים?", a: "חופשה נועדה למנוחה ולהטענת מצברים, וזה חלק בלתי נפרד מהתהליך. אם יש בחופשה חדר כושר ואתם מרגישים בנוח להתאמן בו, זה מעולה ויעזור לכם להישאר עקביים עם התוכנית. אם אין אפשרות או שבחרתם לנוח לגמרי, זה גם בסדר גמור. נסו לשמור על עקרונות בסיסיים: הקפידו על כמות חלבון נאותה ברוב הארוחות והישארו פעילים. כשחוזרים, פשוט חוזרים לשגרה הרגילה בלי 'פיצוי' או 'עונשים' הגוף שלכם יתאזן מהר מאוד." },
            { q: "איך משלבים אלכוהול בתהליך (אם בכלל)?", a: "אלכוהול הוא לא 'מחוץ לתחום', אבל חשוב להבין שהוא מכיל קלוריות ריקות ועלול לעכב את קצב ההתאוששות מהאימונים. אם בחרתם לשתות, העדיפו משקאות עם פחות סוכר כמו יין יבש או משקאות 'נקיים' (וודקה/ג'ין) עם תוספת ללא קלוריות כמו זירו או סודה. שימו לב ששכרות גבוהה פוגעת משמעותית ביכולת של הגוף להשתקם, מה שישפיע ישירות על האימון הבא שלכם ועל קצב התוצאות. נסו להגביל את הכמות והתדירות, והכי חשוב, אל תתנו לאלכוהול להוביל אתכם לזלילה לא מבוקרת של נשנושים, שם נמצא הנזק הקלורי האמיתי." },
            { q: "מרגישים רעב בין הארוחות, מה אפשר לאכול?", a: "רעב הוא חלק טבעי מהתהליך, במיוחד בשלבים של ירידה באחוזי שומן, אבל אין סיבה שתסבלו. הפתרון הכי יעיל הוא לצרוך ירקות חתוכים ללא הגבלה, הם נותנים נפח בקיבה ותחושת שובע עם מינימום קלוריות. בנוסף, הקפידו לשתות כוס מים גדולה, כי לפעמים הגוף מפרש צמא כרעב. אם אתם מרגישים רעב קיצוני, אפשר להזיז מעט מהחלבון של הארוחה הבאה לשלב מוקדם יותר, או לבחור בנשנוש חלבוני דל קלוריות כמו יוגורט חלבון או כמה פריכיות." },
            { q: "האם זה משנה אם אוכלים 3 ארוחות גדולות או 6 קטנות?", a: "מה שקובע את התוצאה הסופית הוא סך הערכים והקלוריות שאתם צורכים לאורך היום, ולא מספר הפעמים שבהן אתם פותחים את המקרר. אין 'קסם' במטבוליזם שאוכלים הרבה ארוחות קטנות. אם נוח לכם יותר לאכול 3 ארוחות משביעות בגלל הלו”ז, זה מצוין. אם אתם מעדיפים 6 ארוחות קטנות כדי לשמור על רמות אנרגיה קבועות, זה גם בסדר. בחרו בשיטה שעוזרת לכם הכי הרבה להיצמד לתפריט שלכם מבלי להרעיב את עצמכם מבלי להרגיש רעב קיצוני או כבדות שתפריע לכם במהלך היום." },
            { q: "האם מותר לשתות משקאות 'זירו' או משקאות ללא קלוריות?", a: "משקאות 'זירו' או משקאות ממותקים בממתיקים מלאכותיים הם כלי מצוין שיכול לעזור לכם להיצמד לתהליך, במיוחד כשמתעורר חשק למתוק מבלי להוסיף קלוריות מיותרות. מבחינת ירידה במשקל, אין איתם שום בעיה והם לא עוצרים את התהליך. עם זאת, חשוב לזכור שהמים הם תמיד המקור הטוב ביותר לנוזלים עבור הגוף שלכם, ולכן כדאי שהם יהיו הבסיס לשתייה לאורך היום. השתמשו במשקאות הדיאט במינון הגיוני כפינוק או כעזר להתגברות על רעב, אך אל תהפכו אותם לתחליף בלעדי למים." },
            { q: "האם מותר לאכול פחמימות בלילה?", a: "חד משמעית כן. המיתוס שפחמימות הופכות לשומן אחרי השעה 20:00 הוא אחד המיתוסים העתיקים והשגויים ביותר. לגוף שלכם אין 'שעון קלוריות' שמתאפס בחצות או מפסיק לעבוד בלילה. מה שקובע אם תעלו בשומן או תרדו הוא סך הקלוריות היומי שלכם. למעשה, עבור אנשים רבים, ארוחה המכילה פחמימה בערב יכולה אפילו לעזור לשינה טובה ורגועה יותר. כל עוד זה נכנס במסגרת התפריט שלכם, אין שום בעיה לאכול פחמימות גם בלילה." },
            { q: "מה קורה אם 'חרגתי' מהתפריט בארוחה אחת או ביום אחד?", a: "שום דבר נורא לא קרה. התהליך שלנו הוא ריצה למרחקים ארוכים, ולארוחה אחת אין כוח להרוס עבודה של שבועות. הטעות הכי גדולה שאפשר לעשות אחרי חריגה היא להיכנס ללחץ, להרעיב את עצמכם למחרת או 'לשבור את הכלים' ולהמשיך לאכול שטויות כי 'היום כבר נהרס'. הפתרון פשוט: ממשיכים הלאה לארוחה הבאה בדיוק לפי התוכנית. עקביות של 90% מהזמן תנצח תמיד 'שלמות' של יומיים שנשברת מהר מאוד." },
            { q: "איך מתמודדים עם דחף למתוק או פחמימה בשעות הערב?", a: "הדחף הזה בדרך כלל מגיע משתי סיבות: או שלא אכלתם מספיק לאורך היום והגוף מחפש אנרגיה זמינה, או שמדובר בהרגל של 'פיצוי' על יום עמוס. הטיפ הראשון שלי הוא לוודא שאתם אוכלים מסודר כמו שצריך במהלך היום, כשאוכלים מספיק חלבון ופחמימות בארוחות הגדולות, הגוף הרבה יותר רגוע בערב. אם בכל זאת הגיע החשק, נסו לסגור את הפינה עם משהו קטן ומבוקר (כמו פרי או מעדן חלבון). לפעמים גם כוס מים גדולה או תה חם יכולים להרגיע את הדחף ולעזור לכם לעבור את הערב בלי 'לפשוט' על המקרר." },
            { q: "מה לעשות אם אני מרגיש רעב מאוד בלילה, רגע לפני השינה?", a: "ללכת לישון רעבים זה לא אידיאלי, כי זה עלול לפגוע באיכות השינה שלכם. אם אתם מרגישים רעב אמיתי רגע לפני השינה, הפתרון הוא לאכול משהו קטן וחלבונים בעיקר (כמו מעדן חלבון או מעט גבינה לבנה). חלבון נספג לאט ועוזר לתחושת שובע וגם להתאוששות השריר במהלך הלילה. כדאי להימנע מארוחות כבדות או עתירות שומן ממש לפני השינה כי הן עלולות להכביד על העיכול. לטווח הארוך, אם זה קורה כל לילה, כדאי שנוסיף קצת יותר אוכל לארוחת הערב שלכם כדי שתגיעו למיטה רגועים." },
            { q: "האם חייב לשקול כל דבר שאוכלים, או שאפשר להעריך 'לפי העין'?", a: "בתחילת הדרך, אני ממליץ בחום לשקול כמה שיותר. הסיבה היא שרובנו גרועים מאוד בלהעריך כמויות 'לפי העין”. כף חמאת בוטנים או כוס אורז יכולות להכיל פי 2 קלוריות ממה שאנחנו חושבים. השקילה היא לא לכל החיים, היא 'בית ספר' שעוזר לכם להבין איך נראות הכמויות שבאמת מקדמות אתכם. ברגע שתפתחו את המיומנות הזאת ותראו שהתוצאות מגיעות בעקביות, נוכל לשחרר קצת ולהסתמך על הערכה, אבל כל עוד אנחנו רוצים דיוק מקסימלי ותוצאות מהירות, המשקל הוא החבר הכי טוב שלכם." },
            { q: "מה עושים אם יש אירוע חברתי בעבודה עם כיבוד שאני לא יכול לשלוט עליו?", a: "הכי חשוב, לא נכנסים ללחץ ולא נמנעים מהאירוע. המטרה היא ללמוד להתנהל בתוך החיים האמיתיים. הטיפ שלי הוא להגיע לאירוע כשאתם לא מורעבים (תאכלו משהו שמכיל חלבון לפני), ואז לבחור בכיבוד את האופציות היותר 'נקיות”, חלבונים, ירקות או פחמימות פשוטות יחסית. תנסו לשמור על 'חוק ה-80/20': אם 80% מהיום שלכם היה מסודר ומדויק, האירוע לא יהרוס כלום. פשוט תהיו מודעים לכמויות, ומיד בארוחה הבאה תחזרו לשגרה." },
            { q: "האם יש הבדל בין פחמימות 'מורכבות' (כמו אורז מלא) לפחמימות 'פשוטות' (כמו אורז לבן) מבחינת תוצאות?", a: "מבחינת ירידה במשקל או בניית שריר, השורה התחתונה היא כמות הקלוריות והפחמימות שצרכתם בסוף היום. הגוף שלכם יודע לפרק את שתיהן לאנרגיה. ההבדל העיקרי הוא בתחושת השובע ובבריאות: פחמימות מורכבות נספגות לאט יותר בדם ומשאירות אתכם שבעים ליותר זמן. עם זאת, אם אתם מעדיפים אורז לבן או פסטה רגילה, זה בסדר גמור! פשוט תשתדלו לשלב לידם ירקות וחלבון כדי להאט את הספיגה ולשמור על שובע. בקיצור: תאכלו מה שטעים לכם ומשתלב לכם בשגרה, כל עוד אתם עקביים בכמויות." }
        ]
    },
    {
        category: "אימונים וביצועים",
        questions: [
            { q: "מתי הזמן הכי טוב להתאמן? בבוקר או בערב?", a: "הזמן הכי טוב להתאמן הוא הזמן שבו אתם הכי עקביים ויכולים להתמיד לאורך זמן. מבחינה פיזיולוגית, אין הבדל משמעותי בשריפת שומן או בבניית שריר בין אימון בוקר לאימון ערב. חלק מהאנשים מרגישים חזקים יותר בערב אחרי שאכלו מספיק במהלך היום, וחלק מעדיפים לסיים עם האימון על הבוקר כדי 'להוריד אותו מהראש'. בחרו את השעה שבה אתם מרגישים הכי עירניים והכי פחות נוטים לבטל, זה הסוד האמיתי לתוצאות." },
            { q: "האם חייבים לאכול מיד אחרי האימון ('חלון ההזדמנויות')?", a: "המושג של 'חלון ההזדמנויות' שבו חייבים לאכול תוך דקות ספורות מסיום האימון הוא ברובו מיתוס. מה שבאמת קובע את התוצאות שלכם הוא סך החלבון, הקלוריות ואיכות התזונה לאורך כל היממה. עם זאת, אחרי אימון עצים הגוף שלכם השתמש באנרגיה רבה, ולכן כדאי ושווה להחזיר לו אנרגיה דרך ארוחה טובה בזמן שנוח לכם לאחר האימון. ארוחה כזו תעזור לכם להתאושש טוב יותר ולהגיע שבעים וחדים לשאר היום, אבל אל תיכנסו ללחץ אם זה לא קורה בשנייה שסיימתם את הסט האחרון." },
            { q: "מה לעשות אם מרגישים חוסר אנרגיה קיצוני לפני אימון?", a: "חוסר אנרגיה יכול לנבוע מכמה גורמים: חוסר בשינה, יום לחוץ בעבודה או פשוט כי לא אכלתם מספיק פחמימות לפני. במצב כזה, נסו קודם כל לאכול פרי או פחמימה זמינה אחרת כ-30 דקות לפני האימון כדי להעלות את רמת הסוכר. אם זה לא עוזר, לפעמים כוס קפה חזק תעשה את העבודה. בכל מקרה, אם הגעתם לאימון ואתם מרגישים סמרטוטים, עדיף לבצע אימון קל יותר או אפילו לוותר ולנוח, מאשר להכריח את הגוף ולבצע אימון לא איכותי שרק יגדיל את העומס." },
            { q: "האם חייבים לעשות אירובי כדי לרדת במשקל?", a: "ממש לא חייבים, אבל זה כלי עזר מעולה. הירידה במשקל נקבעת על ידי הגירעון הקלורי שלכם, כלומר, שאתם מכניסים פחות אנרגיה ממה שאתם מוציאים. אפשר להגיע לזה רק דרך התזונה, אבל אירובי מאפשר לכם להגדיל את ההוצאה האנרגטית, לשפר את בריאות הלב וכלי הדם ולהוסיף עוד 'מרווח ביטחון' בתפריט. ההמלצה שלי היא לשלב אירובי בצורה מתונה שאתם נהנים ממנה (הליכה, שחייה, רכיבה) כתוספת לאימוני הכוח, שהם העיקר בבניית המראה החטוב." },
            { q: "מה עושים בימים שאין מוטיבציה להתאמן?", a: "בואו נהיה כנים, אף אחד לא קם כל בוקר בטירוף לאימון. מוטיבציה זה משהו שבא והולך, אבל מה שמביא תוצאות זה פשוט להופיע. ביום שאין לכם כוח, אל תחכו שהחשק יבוא, פשוט שימו נעליים וצאו. בדרך כלל האנרגיה כבר תגיע תוך כדי תנועה. גם אם בסוף עשיתם אימון קצת פחות חזק מהרגיל, זה עדיין פי אלף יותר טוב מלוותר לעצמכם. בסוף, הניצחונות הכי גדולים קורים דווקא בימים שהיה הכי קשה לצאת מהבית." },
            { q: "איך יודעים מתי הגיע הזמן להעלות משקלי עבודה בתרגילים?", a: "הסימן הכי טוב הוא כשאתם מסיימים את כל הסטים והחזרות שהגדרנו, ומרגישים שהחזרות האחרונות עוברות יחסית 'חלק' ויש לכם יכולת לבצע עוד 2–3 חזרות נוספות בלי לפגוע בטכניקה. במצב כזה, הגיע הזמן להעלות משקל באימון הבא. אני ממליץ להוסיף ממש קצת בכל פעם, זה הכי חכם, בטוח ושומר על התקדמות עקבית בלי להעמיס על הגוף בצורה פתאומית. אם אתם מתלבטים אם להעלות או להישאר, פשוט שלחו לי סרטון של הסט האחרון שלכם ואתן לכם תשובה מדויקת." },
            { q: "מה עושים אם אין בחדר הכושר את המכשיר הספציפי שכתוב בתוכנית?", a: "קודם כל, לא נלחצים, לכל תרגיל יש תחליף מצוין. אם מכשיר מסוים תפוס או לא קיים במכון שלכם, אפשר בדרך כלל לבצע תנועה דומה עם משקולות חופשיות או מכשיר אחר שעובד על אותה קבוצת שרירים. במצב כזה, פשוט תשלחו לי הודעה מהירה בווטסאפ עם מה שזמין לכם בסביבה, ואשלח לכם חלופה שתעשה את העבודה באותה רמה. המטרה היא לא לוותר על התרגיל, אלא להתאים אותו למה שיש." },
            { q: "האם כדאי לעשות אירובי גם אם המטרה היא רק העלאת מסת שריר?", a: "בהחלט כן. למרות שהפוקוס שלנו הוא על אימוני כוח כדי לבנות שריר, לאירובי יש תפקיד חשוב גם כאן. הוא משפר את סיבולת לב הריאה שלכם, מה שמאפשר לכם להתאושש מהר יותר בין סטים ולבצע אימוני כוח אינטנסיביים יותר. בנוסף, אירובי עוזר לשמור על בריאות המטבוליזם ועל אחוז שומן תקין בזמן שאנחנו בעלייה במסה. הסוד הוא במינון, אנחנו לא נגזים כדי לא לשרוף יותר מדי קלוריות שנחוצות לבנייה, אבל שילוב מתון של אירובי רק יתרום לתוצאה הסופית." },
            { q: "האם אימון ארוך יותר (שעתיים+) אומר תוצאות טובות יותר?", a: "ממש לא, ולפעמים אפילו להפך. מה שקובע את התוצאות זה לא כמה זמן העברתם במכון, אלא מה עשיתם בזמן הזה, האיכות והעצימות של האימון. אימון כוח אפקטיבי וממוקד יכול לקחת גם 30 עד 45 דקות. כשמתאמנים שעתיים ומעלה, בדרך כלל זה אומר שיש יותר מדי זמן מנוחה בין הסטים, יותר מדי דיבורים, או שהעצימות פשוט נמוכה מדי. מעבר לזה, אימונים ארוכים מדי גורמים לעייפות מצטברת שפוגעת ביכולת של הגוף להתאושש. המטרה שלנו היא להיכנס, לעבוד חזק ומדויק, ולצאת לאכול ולנוח." },
            { q: "האם נשים צריכות להתאמן שונה מגברים כדי לא להיראות 'שריריות מדי'?", a: "ממש לא. המיתוס שנשים יהפכו ל'מפתחות גוף' רק כי הן מרימות משקולות הוא פשוט לא נכון. לנשים יש הרבה פחות טסטוסטרון מגברים, מה שהופך את תהליך בניית השריר להרבה יותר איטי ומבוקר. אימון כוח אינטנסיבי הוא הדרך הכי טובה של אישה לקבל מראה חטוב, מוצק ומעוצב. מבנה האימון ושיטות העבודה דומים מאוד לשל גברים, ההבדל היחיד יהיה בדרך כלל בהעדפה אישית של דגשים (כמו יותר עבודה על פלג גוף תחתון), אבל הבסיס נשאר זהה: עבודה חזקה עם משקולות תביא לתוצאות הטובות ביותר." },
            { q: "האם זה בסדר לשתות קפה לפני אימון, והאם זה עוזר לביצועים?", a: "לא רק שזה בסדר, זה אפילו מומלץ. קפאין הוא אחד מתוספי התזונה היחידים שהוכחו מחקרית כמשפרי ביצועים, הוא עוזר לריכוז, מפחית מעט את תחושת המאמץ ומעלה את רמת האנרגיה. קפה שחור או אספרסו כ-30 עד 45 דקות לפני האימון יכולים לתת לכם דחיפה מצוינת. רק שימו לב לא להגזים בכמויות אם אתם מתאמנים בשעות הערב המאוחרות, כדי לא לפגוע באיכות השינה שלכם." }
        ]
    },
    {
        category: "מעקב, התקדמות ובריאות",
        questions: [
            { q: "כמה שעות שינה באמת חייבים כדי לראות תוצאות?", a: "השינה היא הזמן שבו הגוף מבצע את התיקונים והבנייה בפועל. בזמן שאתם ישנים, מופרשים הורמונים קריטיים לבניית מסת שריר ולפירוק תאי שומן. מחסור בשינה מעלה את רמות הורמון הלחץ והרעב, מה שמקשה מאוד על השליטה בתפריט ופוגע בכוח שלכם באימונים. השאיפה היא לישון בין 7 ל-9 שעות בלילה. אם אתם ישנים משמעותית פחות מזה, יהיה לכם קשה הרבה יותר לראות את התוצאות שהשקעתם עבורן במטבח ובחדר הכושר." },
            { q: "השרירים תפוסים ממש, להתאמן בכל זאת?", a: "באופן כללי, אני ממליץ לא להתאמן כשהשרירים תפוסים (DOMS) כדי לאפשר לגוף את זמן ההתאוששות שהוא זקוק לו. במידה ואתם מרגישים כאב חד, נקודתי, מגביל בטווח התנועה או פשוט כאב שיוצא מגדר הרגיל, אל תנסו 'לנצח' אותו. במקרים כאלו, אני מבקש שתעצרו ותדברו איתי מיד כדי שנוכל לבחון את המצב ולמנוע פציעות מיותרות. הבריאות שלכם היא בעדיפות עליונה." },
            { q: "מה עושים אם המשקל 'נתקע' לכמה ימים?", a: "קודם כל, בלי פאניקה. המשקל הוא לא המדד היחיד להתקדמות. הגוף שלנו נוטה לצבור נוזלים מסיבות רבות: אימון חזק מדי, צריכת נתרן גבוהה, לחץ או חוסר בשינה. יכול להיות שאתם יורדים בשומן ועולים במסת שריר במקביל, מה שגורם למספר על המשקל להישאר זהה. המדדים האמיתיים הם המראה במראה, איך הבגדים יושבים עליכם וההיקפים. אם המשקל תקוע יותר משבועיים-שלושה למרות הקפדה מלאה על התפריט, אז נבצע התאמות, אבל כמה ימים של 'סטנד-ביי' הם חלק נורמלי לחלוטין מהתהליך." },
            { q: "האם חייבים להישקל כל יום או פעם בשבוע?", a: "ההמלצה שלי היא להישקל כל בוקר (אחרי שירותים ולפני אוכל) ולחשב ממוצע שבועי. למה? כי המשקל שלנו תנודתי מאוד ומושפע מנוזלים, שינה ומתח. אם נשקלים רק פעם בשבוע, אתם יכולים ליפול על יום של אגירת נוזלים ולחשוב שלא התקדמתם, כשבפועל המגמה היא מצוינת. הממוצע השבועי נותן לנו את התמונה האמיתית. עם זאת, אם השקילה היומית עושה לכם רע ברמה המנטלית, נדבר על זה ונתאים את המעקב למה שנוח לכם, הכי חשוב שנראה התקדמות במראה." },
            { q: "מה לעשות אם הגענו ל'פלאטו' (תקיעה) והמשקל לא זז כבר שבועיים?", a: "קודם כל, לנשום עמוק, זה קורה לכולם וזה חלק טבעי מהתהליך. אם המשקל באמת תקוע (בממוצע השבועי שלו) יותר משבועיים, זה הסימן שלנו לעשות חישוב מסלול מחדש. יכול להיות שהגוף שלכם הסתגל לרמת הקלוריות הנוכחית וצריך 'לתת לו דחיפה' דרך שינוי קטן בתפריט או הוספה של מעט פעילות אירובית. לפני שאנחנו נוגעים באוכל, אני תמיד בודק איתכם: האם השינה הייתה טובה? האם רמת הסטרס עלתה? והאם באמת דייקנו בכמויות? ברגע שנבין את התמונה המלאה, נבצע התאמה שתחזיר אתכם למסלול הירידה." },
            { q: "מה עושים אם חולים (למשל עם חום)?", a: "בריאות היא תמיד בעדיפות ראשונה. אם אתם חולים, עם חום או מרגישים חולשה קיצונית, עוצרים הכל ונחים. אין שום טעם לנסות 'להילחם' בזה וללכת להתאמן; זה רק יאריך את זמן המחלה ויפגע בהתאוששות של הגוף. מבחינת תזונה, אל תנסו להיות בגרעון קלורי נוקשה בזמן מחלה, הגוף שלכם צריך אנרגיה כדי להחלים. תשתדלו לאכול לפי תחושת הרעב, להתמקד בחלבון ולשתות המון מים. ברגע שתרגישו טוב ותחזרו לעצמכם, נחזור לתוכנית בהדרגה. אל תדאגו, כמה ימי מנוחה לא יהרסו את התוצאות שלכם." },
            { q: "האם יש טעם להתאמן אם ישנים רק 4–5 שעות בלילה?", a: "זה תלוי בהרגשה שלכם, אבל בגדול, התשובה היא כן, כל עוד זה לא הופך להרגל קבוע. מה שחשוב להבין זה שאימון אחרי לילה כזה צריך להיות קצת פחות אינטנסיבי מהרגיל. לא בצורה דרסטית, אבל כן להוריד מעט רגל מהגז כי הגוף נמצא במחסור באנרגיה והסיכון לפציעה עולה. אם אתם מרגישים סחרחורות או חולשה קיצונית, עדיף לוותר, לישון מוקדם ולחזור חזקים למחרת. תזכרו שהשריר נבנה במנוחה, אימון בלי שינה זה כמו לנסות לנסוע ברכב בלי דלק. אם זה קורה פעם ב... תופיעו, תעשו אימון קצת יותר רגוע, ותמשיכו הלאה." },
            { q: "האם 'יום חופש' מאימונים אומר שצריך לאכול פחות קלוריות באותו יום?", a: "ממש לא. הגוף שלכם בונה ומשקם את השרירים דווקא בימי המנוחה, והוא זקוק לאנרגיה ולחלבון כדי לבצע את התהליך הזה בצורה מיטבית. יום מנוחה הוא לא יום 'בזבוז', הוא חלק בלתי נפרד מההתקדמות. אנחנו שומרים על עקביות באכילה כדי לתת לגוף תנאים יציבים להתאוששות. אז תאכלו רגיל, תנו לגוף לנוח, ותגיעו לאימון הבא חזקים יותר." },
            { q: "איך חוזרים לשגרה אחרי תקופה ארוכה של הפסקה (מחלה, מילואים, תקופה עמוסה)?", a: "הטעות הכי גדולה היא לנסות לחזור ישר ל-200% מהנקודה שבה הפסקתם. אחרי הפסקה, הגוף צריך הסתגלות מחודשת. נחזור בהדרגה, גם במשקלים וגם בנפח האימון (פחות סטים בשבוע הראשון). המטרה היא להחזיר את הגוף לתנועה בלי לגרום לפציעות או לכאבי שרירים משתקים שיגרמו לכם לעצור שוב. תנו לעצמכם שבוע-שבועיים של 'כניסה חזרה לעניינים' ותראו שהכוח והסיבולת חוזרים הרבה יותר מהר ממה שאתם חושבים. הכי חשוב זה פשוט להתחיל, גם אם האימון הראשון מרגיש 'חלש'." },
            { q: "האם חייבים לקנות אבקת חלבון או קריאטין כדי לראות תוצאות?", a: "ממש לא חייבים. אבקת חלבון היא בסך הכל כלי נוח (וזמין) לעזור לכם להגיע למכסת החלבון היומית שלכם, בדיוק כמו חזה עוף, ביצים או גבינות. אם אתם מצליחים להגיע לכמות החלבון הנדרשת מהאוכל הרגיל, אין צורך באבקה. לגבי קריאטין, זהו אחד התוספים הנחקרים והיעילים ביותר לשיפור כוח ומסה, אך הוא נחשב ל'בונוס' בלבד. התוצאות שלכם יגיעו קודם כל בזכות אימונים חזקים, תזונה נכונה ושינה מספקת. התוספים הם רק ה-5% האחרונים שמשלימים את התמונה." }
        ]
    }
];
